import { TERRAIN_HALF_SIZE } from "@/terrain/constants";
import { wissahickon } from "@/terrain/wissahickonHeightField";

/**
 * Heightfield backed by real elevation from the Wissahickon Creek watershed.
 *
 * Instead of a procedural noise field, the terrain samples a raster digital
 * elevation model (DEM) generated by `scripts/generate-wissahickon-dem.ts`
 * from AWS Terrain Tiles (Mapzen "terrarium"). The generator covers a bounding
 * box that contains the whole main stem of the creek - from the north-west
 * headwaters down to the confluence with the Schuylkill - so the relief is a
 * genuine single-channel valley, not a synthetic bowl.
 *
 * `calculateHeight` maps the enlarged terrain: the mesh now spans -20..+20
 * in both axes while the DEM bounding box still covers the central -6..+6,
 * so positions beyond the box clamp to the nearest DEM edge and the world
 * stays filled with terrain. Both the mesh builder
 * (`createTerrainGeometry`) and the displacement texture builder keep
 * sampling the identical field.
 *
 * Real elevation is measured in metres (about 2.6 m at the creek bed up to
 * about 135 m on the surrounding ridges). That is mapped into the scene's
 * vertical envelope by a percentile clamp: the p05 elevation sits at the valley
 * datum and p95 sits at the ridge datum, so a handful of outlier cliffs or a
 * deep channel never crushes the rest of the landscape into flatness.
 */

/** Vertical envelope that the scene was framed and lit around. */
const VALLEY_DATUM = -0.5;
const RIDGE_DATUM = 1.3;

/**
 * Percentiles used as the low/high anchors for the vertical mapping, so that a
 * few extreme cells (a cul-de-sic, a quarry, a tile seam) do not dominate.
 */
const LOW_ANCHOR_PERCENTILE = 0.05;
const HIGH_ANCHOR_PERCENTILE = 0.95;

/** Number of metres per decoded grid unit in the generated data file. */
const METRES_PER_UNIT = wissahickon.heightScale;

/**
 * Decode the committed base64 grid once at module load into an array of metres.
 * Each grid value was stored as tenths-of-a-metre Int16, so dividing by the
 * height scale recovers metres.
 */
const decodeHeightMeters = (): Float32Array => {
  const binary = Uint8Array.from(atob(wissahickon.data), (character) =>
    character.charCodeAt(0),
  );
  const view = new DataView(binary.buffer);
  const grid = new Float32Array(
    wissahickon.resolution * wissahickon.resolution,
  );

  for (let index = 0; index < grid.length; index += 1) {
    grid[index] = view.getInt16(index * 2, true) / METRES_PER_UNIT;
  }

  return grid;
};

/**
 * Build a bilinear sampler over the DEM grid, mapping local-plane coordinates
 * (-6..+6 on each axis) to grid coordinates and clamping to the edges.
 */
const createHeightSampler = (
  meters: Float32Array,
): ((x: number, y: number) => number) => {
  const { resolution } = wissahickon;

  // Anchor the vertical mapping to robust percentiles of the real data.
  const sorted = Float32Array.from(meters).sort(
    (first, second) => first - second,
  );
  const lowAnchor =
    sorted[Math.round(LOW_ANCHOR_PERCENTILE * (sorted.length - 1))];
  const highAnchor =
    sorted[Math.round(HIGH_ANCHOR_PERCENTILE * (sorted.length - 1))];

  // Guard against a degenerate (perfectly flat) source so the mapping stays finite.
  const spread = highAnchor - lowAnchor || 1;

  return (x: number, y: number): number => {
    // Fractional grid coordinates for the requested world position.
    const gridX =
      ((x + TERRAIN_HALF_SIZE) / (2 * TERRAIN_HALF_SIZE)) * (resolution - 1);
    const gridY =
      ((y + TERRAIN_HALF_SIZE) / (2 * TERRAIN_HALF_SIZE)) * (resolution - 1);

    const baseX = Math.max(0, Math.min(resolution - 1, Math.floor(gridX)));
    const baseY = Math.max(0, Math.min(resolution - 1, Math.floor(gridY)));
    const nextX = Math.min(resolution - 1, baseX + 1);
    const nextY = Math.min(resolution - 1, baseY + 1);

    // Weights are relative to the clamped base cell, so edge samples land on
    // the border texel rather than reaching off the array.
    const weightX = Math.max(0, Math.min(1, gridX - baseX));
    const weightY = Math.max(0, Math.min(1, gridY - baseY));

    const heightAt = (column: number, row: number): number =>
      meters[row * resolution + column];

    const topLeft = heightAt(baseX, baseY);
    const topRight = heightAt(nextX, baseY);
    const bottomLeft = heightAt(baseX, nextY);
    const bottomRight = heightAt(nextX, nextY);

    const top = topLeft + (topRight - topLeft) * weightX;
    const bottom = bottomLeft + (bottomRight - bottomLeft) * weightX;
    const elevation = top + (bottom - top) * weightY;

    // Clamp to the anchors, then map into the scene's vertical envelope.
    const normalised =
      (Math.max(lowAnchor, Math.min(highAnchor, elevation)) - lowAnchor) /
      spread;

    return VALLEY_DATUM + normalised * (RIDGE_DATUM - VALLEY_DATUM);
  };
};

const sampler = createHeightSampler(decodeHeightMeters());

/**
 * Calculate terrain height (world Y) at a local-plane position, sampled from
 * the real Wissahickon DEM. Coordinates are on the terrain mesh (-20..+20 on
 * each axis); out-of-range positions clamp to the nearest edge.
 */
export const calculateHeight = (x: number, y: number): number => sampler(x, y);
