import { cobbsCreek } from "@/terrain/cobbsCreekHeightField";
import { TERRAIN_HALF_SIZE } from "@/terrain/constants";

/**
 * Heightfield backed by real elevation from the Cobbs Creek valley, in the
 * tight window centred on the Cedar Park neighbourhood of Philadelphia.
 *
 * Instead of a procedural noise field, the terrain samples a raster digital
 * elevation model (DEM) generated by `scripts/generate-cobbs-creek-dem.ts`
 * from AWS Terrain Tiles (Mapzen "terrarium"). The window is only about 6 km
 * across - it frames the stretch of valley that runs past Cedar Park rather
 * than the whole 19 km creek: Cobbs Creek (source about 115 m in Montgomery
 * County, mouth at sea level on Darby Creek) enters from the north-west and
 * runs off the south edge, so the relief is a genuine valley rather than a
 * synthetic bowl. Cedar Park sits on the drainage divide between the Cobbs
 * Creek valley and the Schuylkill, so the neighbourhood is the inter-valley
 * ridge at the centre of the window and both channels cross the scene to its
 * west and east.
 *
 * `calculateHeight` maps the whole terrain: the mesh spans -20..+20 in both
 * axes and the DEM bounding box fills that span, so only positions beyond the
 * box clamp to the nearest DEM edge. Both the mesh builder
 * (`createTerrainGeometry`) and the displacement texture builder keep
 * sampling the identical field.
 *
 * Real elevation is measured in metres (about -1 m in the channel lows up to
 * about 65 m on the rising ground toward the Cobbs Creek headwaters). That is
 * mapped into the scene's vertical envelope by a percentile clamp: the p05
 * elevation sits at the valley datum and p95 sits at the ridge datum, so a
 * handful of outlier cliffs or a deep channel never crushes the rest of the
 * landscape into flatness.
 */

/** Vertical envelope that the scene was framed and lit around. */
const VALLEY_DATUM = -0.5;
const RIDGE_DATUM = 1.3;

/**
 * Percentiles used as the low/high anchors for the vertical mapping, so that a
 * few extreme cells (a cul-de-sac, a quarry, a tile seam) do not dominate.
 */
const LOW_ANCHOR_PERCENTILE = 0.05;
const HIGH_ANCHOR_PERCENTILE = 0.95;

/** Number of metres per decoded grid unit in the generated data file. */
const METRES_PER_UNIT = cobbsCreek.heightScale;

/**
 * Decode the committed base64 grid once at module load into an array of metres.
 * Each grid value was stored as tenths-of-a-metre Int16, so dividing by the
 * height scale recovers metres.
 */
const decodeHeightMeters = (): Float32Array => {
  const binary = Uint8Array.from(atob(cobbsCreek.data), (character) =>
    character.charCodeAt(0),
  );
  const view = new DataView(binary.buffer);
  const grid = new Float32Array(cobbsCreek.resolution * cobbsCreek.resolution);

  for (let index = 0; index < grid.length; index += 1) {
    grid[index] = view.getInt16(index * 2, true) / METRES_PER_UNIT;
  }

  return grid;
};

/**
 * Build a bilinear sampler over the DEM grid, mapping local-plane coordinates
 * (-20..+20 on each axis, about 6 km of real ground) to grid coordinates and
 * clamping to the edges.
 */
const createHeightSampler = (
  meters: Float32Array,
): ((x: number, y: number) => number) => {
  const { resolution } = cobbsCreek;

  // Anchor the vertical mapping to robust percentiles of the real data.
  const sorted = Float32Array.from(meters).sort(
    (first, second) => first - second,
  );
  const lowAnchor =
    sorted[Math.round(LOW_ANCHOR_PERCENTILE * (sorted.length - 1))];
  const highAnchor =
    sorted[Math.round(HIGH_ANCHOR_PERCENTILE * (sorted.length - 1))];

  // Guard against a degenerate (perfectly flat) source so the mapping stays finite.
  const spread = highAnchor - lowAnchor || 1;

  return (x: number, y: number): number => {
    // Fractional grid coordinates for the requested world position.
    const gridX =
      ((x + TERRAIN_HALF_SIZE) / (2 * TERRAIN_HALF_SIZE)) * (resolution - 1);
    const gridY =
      ((y + TERRAIN_HALF_SIZE) / (2 * TERRAIN_HALF_SIZE)) * (resolution - 1);

    const baseX = Math.max(0, Math.min(resolution - 1, Math.floor(gridX)));
    const baseY = Math.max(0, Math.min(resolution - 1, Math.floor(gridY)));
    const nextX = Math.min(resolution - 1, baseX + 1);
    const nextY = Math.min(resolution - 1, baseY + 1);

    // Weights are relative to the clamped base cell, so edge samples land on
    // the border texel rather than reaching off the array.
    const weightX = Math.max(0, Math.min(1, gridX - baseX));
    const weightY = Math.max(0, Math.min(1, gridY - baseY));

    const heightAt = (column: number, row: number): number =>
      meters[row * resolution + column];

    const topLeft = heightAt(baseX, baseY);
    const topRight = heightAt(nextX, baseY);
    const bottomLeft = heightAt(baseX, nextY);
    const bottomRight = heightAt(nextX, nextY);

    const top = topLeft + (topRight - topLeft) * weightX;
    const bottom = bottomLeft + (bottomRight - bottomLeft) * weightX;
    const elevation = top + (bottom - top) * weightY;

    // Clamp to the anchors, then map into the scene's vertical envelope.
    const normalised =
      (Math.max(lowAnchor, Math.min(highAnchor, elevation)) - lowAnchor) /
      spread;

    return VALLEY_DATUM + normalised * (RIDGE_DATUM - VALLEY_DATUM);
  };
};

const sampler = createHeightSampler(decodeHeightMeters());

/**
 * Calculate terrain height (world Y) at a local-plane position, sampled from
 * the real Cobbs Creek DEM. Coordinates are on the terrain mesh (-20..+20 on
 * each axis); out-of-range positions clamp to the nearest edge.
 */
export const calculateHeight = (x: number, y: number): number => sampler(x, y);
